### ISSUE TITLE
OxfordRobotCar_CVM problem

### ISSUE THREAD

**Issue by Machine-NO-Learning** [tudelft-iv/Visual-Localization-with-Spatial-Prior#3]
Hi, Z.Xia

Hope you are doing well, 

I have some problems with OxfordRobotCar_CVM, in OxfordRobotCar_CVM.tar.gz, there is no 2014-11-28-12-07-13 dataset, but there is a named 2014-11-18-13-20-12 dataset, especially in the 2014-11-18-13-20-12  there is 2014-11-28-12-07-13_lookup.txt, it seems not alignment with this  2014-11-18-13-20-12 dataset, what's wrong with that thanks.

Thanks and cheers.

Hope to get your feedback

**Comment by ZiminXia** [comment]
Updated data provided now.
